
/* ===== ACROW V4.1 ENTRY SCREEN ===== */
(function(){
  const gate=document.getElementById("loginScreen");
  const enter=document.getElementById("enterAppBtn");
  if(!gate || !enter) return;
  enter.addEventListener("click", function(){
    document.body.classList.remove("acrow-app-locked");
    gate.classList.add("acrow-hide");
    setTimeout(function(){ gate.remove(); }, 380);
  });
})();

const DB_NAME="ACROW_MACHINE_GUIDE_V4", DB_VER=1, BUTTONS="buttons", FAULTS="faults";
let db, currentFilter="all", scanner=null, searchTimer=null, editingButtonImage=null, editingFaultImage=null;

const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const norm=v=>String(v??"").toLowerCase().normalize("NFKC").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/ـ/g,"").replace(/[\u064B-\u065F\u0670]/g,"").trim();
const uid=()=>Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8);
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove("show"),2200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(BUTTONS)){const s=d.createObjectStore(BUTTONS,{keyPath:"id"});s.createIndex("machine","machine");s.createIndex("name","name");s.createIndex("code","code")}if(!d.objectStoreNames.contains(FAULTS)){const s=d.createObjectStore(FAULTS,{keyPath:"id"});s.createIndex("buttonId","buttonId");s.createIndex("code","code");s.createIndex("name","name")}};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function store(name,mode="readonly"){return db.transaction(name,mode).objectStore(name)}
function getAll(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function put(name,obj){return new Promise((res,rej)=>{const r=store(name,"readwrite").put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function del(name,id){return new Promise((res,rej)=>{const r=store(name,"readwrite").delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function seed(){const bs=await getAll(BUTTONS);if(bs.length)return;const b={id:uid(),machine:"ماكينة 999",screen:"Main Screen",name:"START",number:"1",code:"M999-START",desc:"زر بدء دورة التشغيل.",image:"",createdAt:Date.now()};await put(BUTTONS,b);await put(FAULTS,{id:uid(),buttonId:b.id,code:"F001",name:"مثال عطل",desc:"مثال توضيحي يمكن تعديله أو حذفه.",solution:"1. أوقف الماكينة بأمان.\n2. افحص سبب العطل.\n3. نفذ الإجراء المناسب.\n4. أعد التشغيل بعد التأكد من السلامة.",image:"",createdAt:Date.now()})}
async function readFile(file){return new Promise((res,rej)=>{if(!file)return res("");const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
function resetButton(){ $("buttonFormEl").reset();$("buttonId").value="";editingButtonImage=null;$("bImagePreview").innerHTML=""}
function resetFault(){ $("faultFormEl").reset();$("faultId").value="";editingFaultImage=null;$("fImagePreview").innerHTML=""}
async function refreshStats(){const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]);$("statMachines").textContent=new Set(bs.map(x=>x.machine).filter(Boolean)).size;$("statButtons").textContent=bs.length;$("statFaults").textContent=fs.length;$("statImages").textContent=bs.filter(x=>x.image).length+fs.filter(x=>x.image).length}
function buttonById(bs,id){return bs.find(x=>x.id===id)}
async function populateFaultButtons(){const bs=await getAll(BUTTONS);$("fButton").innerHTML=bs.sort((a,b)=>a.name.localeCompare(b.name)).map(b=>`<option value="${esc(b.id)}">${esc(b.machine)} — ${esc(b.name)}${b.code?" — "+esc(b.code):""}</option>`).join("")}
function matchButton(b,q){const s=[b.machine,b.screen,b.name,b.number,b.code,b.desc].map(norm).join(" ");return !q||s.includes(norm(q))}
function matchFault(f,bs,q){const b=buttonById(bs,f.buttonId);const s=[f.code,f.name,f.desc,f.solution,b?.machine,b?.screen,b?.name,b?.number,b?.code].map(norm).join(" ");return !q||s.includes(norm(q))}
async function doSearch(q=$("globalSearch").value){q=q.trim();const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]);let out=[];if(currentFilter!=="fault")bs.filter(b=>matchButton(b,q)).slice(0,80).forEach(b=>out.push({type:"button",data:b}));if(currentFilter!=="button")fs.filter(f=>matchFault(f,bs,q)).slice(0,120).forEach(f=>out.push({type:"fault",data:f,button:buttonById(bs,f.buttonId)}));$("resultCount").textContent=out.length?`(${out.length})`:"";$("searchStatus").textContent=q?`تم العثور على ${out.length} نتيجة`:"اكتب كلمة للبحث…";renderResults(out)}
function renderResults(out){const box=$("results");if(!out.length){box.className="results empty";box.innerHTML=`<div class="empty-icon">🔎</div><h3>لا توجد نتائج</h3><p>جرّب اسم الزر أو رقم الـ Fault أو كلمة من وصف المشكلة.</p>`;return}box.className="results";box.innerHTML=out.map((x,i)=>x.type==="button"?buttonCard(x.data):faultCard(x.data,x.button)).join("")}
function buttonCard(b){return `<article class="card"><span class="tag">🔘 زر</span><h4>${esc(b.name)}</h4><div class="meta">🏭 ${esc(b.machine)}<br>🖥 ${esc(b.screen||"—")}<br>🔢 ${esc(b.number||"—")} &nbsp; QR: ${esc(b.code||"—")}</div><div class="card-actions"><button class="small-btn" onclick="showButton('${b.id}')">فتح التفاصيل</button><button class="small-btn" onclick="showQR('${esc(b.code||b.id)}')">QR</button></div></article>`}
function faultCard(f,b){return `<article class="card"><span class="tag">🔧 Fault</span><h4>${esc(f.code)} — ${esc(f.name)}</h4><div class="meta">🔘 ${esc(b?.name||"غير مرتبط")}<br>🏭 ${esc(b?.machine||"—")}<br>${esc(f.desc||"")}</div><div class="card-actions"><button class="small-btn" onclick="showFault('${f.id}')">طريقة الحل</button></div></article>`}
async function showButton(id){const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]);const b=bs.find(x=>x.id===id);if(!b)return;const faults=fs.filter(f=>f.buttonId===id);$("detailSection").classList.remove("hidden");$("detail").innerHTML=`<div class="detail-wrap"><div class="detail-grid"><div>${b.image?`<img class="detail-image" src="${b.image}" alt="">`:`<div class="detail-image" style="height:200px;display:grid;place-items:center">🔘 لا توجد صورة</div>`}</div><div class="detail"><span class="tag">🔘 زر</span><h2>${esc(b.name)}</h2><p class="muted">🏭 ${esc(b.machine)} &nbsp; | &nbsp; 🖥 ${esc(b.screen||"—")} &nbsp; | &nbsp; 🔢 ${esc(b.number||"—")}</p><p>${esc(b.desc||"لا يوجد وصف.")}</p><h3>🔧 الأعطال المرتبطة (${faults.length})</h3>${faults.length?faults.map(f=>`<div class="fault-box"><h4>${esc(f.code)} — ${esc(f.name)}</h4><p>${esc(f.desc||"")}</p><div class="solution">${esc(f.solution||"لا توجد طريقة حل مسجلة.")}</div>${f.image?`<img class="detail-image" style="max-height:220px;margin-top:10px" src="${f.image}" alt="">`:""}<div class="card-actions"><button class="small-btn" onclick="editFault('${f.id}')">✏️ تعديل</button></div></div>`).join(""):`<p class="muted">لا توجد أعطال مرتبطة بهذا الزر.</p>`}</div></div></div>`;$("detailSection").scrollIntoView({behavior:"smooth",block:"start"})}
async function showFault(id){const fs=await getAll(FAULTS);const f=fs.find(x=>x.id===id);if(!f)return;await showButton(f.buttonId);setTimeout(()=>{$("detailSection").scrollIntoView({behavior:"smooth",block:"start"})},30)}
function openAdmin(){ $("adminSection").classList.remove("hidden");populateFaultButtons();renderManage();$("adminSection").scrollIntoView({behavior:"smooth"})}
function closeAdmin(){ $("adminSection").classList.add("hidden")}
async function saveButton(e){e.preventDefault();const id=$("buttonId").value||uid();const old=(await getAll(BUTTONS)).find(x=>x.id===id);const file=$("bImage").files[0];const image=file?await readFile(file):(editingButtonImage??"");const obj={id,machine:$("bMachine").value.trim(),screen:$("bScreen").value.trim(),name:$("bName").value.trim(),number:$("bNumber").value.trim(),code:$("bCode").value.trim(),desc:$("bDesc").value.trim(),image,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};await put(BUTTONS,obj);toast("تم حفظ الزر بنجاح");resetButton();await refreshStats();await populateFaultButtons();await renderManage();doSearch();$("globalSearch").focus()}
async function saveFault(e){e.preventDefault();const id=$("faultId").value||uid();const old=(await getAll(FAULTS)).find(x=>x.id===id);const file=$("fImage").files[0];const image=file?await readFile(file):(editingFaultImage??"");const obj={id,buttonId:$("fButton").value,code:$("fCode").value.trim(),name:$("fName").value.trim(),desc:$("fDesc").value.trim(),solution:$("fSolution").value.trim(),image,createdAt:old?.createdAt||Date.now(),updatedAt:Date.now()};await put(FAULTS,obj);toast("تم حفظ العطل بنجاح");resetFault();await refreshStats();await renderManage();doSearch()}
async function editButton(id){const bs=await getAll(BUTTONS),b=bs.find(x=>x.id===id);if(!b)return;$("buttonId").value=b.id;$("bMachine").value=b.machine||"";$("bScreen").value=b.screen||"";$("bName").value=b.name||"";$("bNumber").value=b.number||"";$("bCode").value=b.code||"";$("bDesc").value=b.desc||"";editingButtonImage=b.image||"";$("bImagePreview").innerHTML=b.image?`<img src="${b.image}">`:"";switchAdminTab("buttonForm");openAdmin();$("bName").focus()}
async function editFault(id){const fs=await getAll(FAULTS),f=fs.find(x=>x.id===id);if(!f)return;$("faultId").value=f.id;await populateFaultButtons();$("fButton").value=f.buttonId;$("fCode").value=f.code||"";$("fName").value=f.name||"";$("fDesc").value=f.desc||"";$("fSolution").value=f.solution||"";editingFaultImage=f.image||"";$("fImagePreview").innerHTML=f.image?`<img src="${f.image}">`:"";switchAdminTab("faultForm");openAdmin();$("fName").focus()}
async function deleteButton(id){if(!confirm("حذف الزر سيحذف الأعطال المرتبطة به أيضًا. هل تريد المتابعة؟"))return;const fs=await getAll(FAULTS);for(const f of fs.filter(x=>x.buttonId===id))await del(FAULTS,f.id);await del(BUTTONS,id);toast("تم حذف الزر والبيانات المرتبطة");await refreshStats();await renderManage();doSearch()}
async function deleteFault(id){if(!confirm("هل تريد حذف هذا العطل؟"))return;await del(FAULTS,id);toast("تم حذف العطل");await refreshStats();await renderManage();doSearch()}
async function renderManage(){const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]),q=norm($("manageSearch")?.value||"");const rows=[];bs.forEach(b=>{if(!q||norm([b.machine,b.screen,b.name,b.code,b.number,b.desc].join(" ")).includes(q))rows.push(`<div class="manage-item"><div><b>🔘 ${esc(b.name)}</b><div class="muted">${esc(b.machine)} — ${esc(b.screen||"—")} — QR: ${esc(b.code||"—")} — ${fs.filter(f=>f.buttonId===b.id).length} أعطال</div></div><div class="manage-actions"><button class="small-btn" onclick="editButton('${b.id}')">✏️</button><button class="small-btn danger" onclick="deleteButton('${b.id}')">🗑️</button></div></div>`)});fs.forEach(f=>{const b=bs.find(x=>x.id===f.buttonId);if(!q||norm([f.code,f.name,f.desc,f.solution,b?.name,b?.machine].join(" ")).includes(q))rows.push(`<div class="manage-item"><div><b>🔧 ${esc(f.code)} — ${esc(f.name)}</b><div class="muted">زر: ${esc(b?.name||"—")} — ${esc(b?.machine||"—")}</div></div><div class="manage-actions"><button class="small-btn" onclick="editFault('${f.id}')">✏️</button><button class="small-btn danger" onclick="deleteFault('${f.id}')">🗑️</button></div></div>`)});$("manageList").innerHTML=rows.length?rows.join(""):`<p class="muted">لا توجد بيانات.</p>`}
function switchAdminTab(id){document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));document.querySelectorAll(".admin-tab-content").forEach(x=>x.classList.toggle("hidden",x.id!==id))}
async function backup(){const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]);const blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),buttons:bs,faults:fs})],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ACROW_Machine_Guide_Backup.json";a.click();URL.revokeObjectURL(a.href);toast("تم إنشاء النسخة الاحتياطية")}
async function restore(file){try{const obj=JSON.parse(await file.text());if(!Array.isArray(obj.buttons)||!Array.isArray(obj.faults))throw Error();for(const b of obj.buttons)await put(BUTTONS,b);for(const f of obj.faults)await put(FAULTS,f);toast("تم استعادة البيانات");await refreshStats();await populateFaultButtons();await renderManage();doSearch()}catch(e){alert("ملف النسخة الاحتياطية غير صحيح.")}}
function showQR(code){const modal=$("qrModal");modal.classList.remove("hidden");$("scanResult").innerHTML=`كود الزر: <b>${esc(code)}</b><br><small>يمكن استخدام هذا الكود في QR خارجي أو ملصق على الماكينة.</small>`}
async function startScanner(){if(scanner)return;const modal=$("qrModal");modal.classList.remove("hidden");$("reader").innerHTML="";if(!window.Html5Qrcode){$("reader").innerHTML=`<p class="muted">ماسح QR يحتاج اتصال إنترنت لتحميل مكتبة الكاميرا أول مرة.</p>`;return}scanner=new Html5Qrcode("reader");try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:220},async text=>{await scanner.stop();scanner.clear();scanner=null;modal.classList.add("hidden");const [bs,fs]=await Promise.all([getAll(BUTTONS),getAll(FAULTS)]);const b=bs.find(x=>x.code===text.trim()||x.id===text.trim());if(b){$("globalSearch").value=b.name;await showButton(b.id)}else{const f=fs.find(x=>x.code===text.trim());if(f)showFault(f.id);else{ $("globalSearch").value=text;doSearch(text);toast("تم قراءة QR لكن الكود غير مسجل");}}},()=>{});}catch(e){scanner=null;$("reader").innerHTML="<p class='muted'>تعذر تشغيل الكاميرا. تأكد من صلاحية الكاميرا واستخدام HTTPS أو localhost.</p>"}}
async function stopScanner(){if(scanner){try{await scanner.stop();scanner.clear()}catch(e){}scanner=null}}
async function init(){await openDB();await seed();await refreshStats();await populateFaultButtons();doSearch();$("globalSearch").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>doSearch(),80)});$("clearSearch").onclick=()=>{$("globalSearch").value="";doSearch();$("globalSearch").focus()};$("scanBtn").onclick=startScanner;$("adminBtn").onclick=openAdmin;$("closeAdmin").onclick=closeAdmin;$("closeDetail").onclick=()=>$("detailSection").classList.add("hidden");$("backupBtn").onclick=backup;$("restoreInput").onchange=e=>e.target.files[0]&&restore(e.target.files[0]);$("buttonFormEl").onsubmit=saveButton;$("faultFormEl").onsubmit=saveFault;$("resetButtonForm").onclick=resetButton;$("resetFaultForm").onclick=resetFault;$("manageSearch").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderManage,80)});document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;doSearch()});document.querySelectorAll(".admin-tab").forEach(b=>b.onclick=()=>switchAdminTab(b.dataset.tab));$("bImage").onchange=async e=>{const x=await readFile(e.target.files[0]);$("bImagePreview").innerHTML=x?`<img src="${x}">`:""};$("fImage").onchange=async e=>{const x=await readFile(e.target.files[0]);$("fImagePreview").innerHTML=x?`<img src="${x}">`:""};document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{if(x.dataset.close==="qrModal"){stopScanner();$("qrModal").classList.add("hidden")}})}
window.showButton=showButton;window.showFault=showFault;window.showQR=showQR;window.editButton=editButton;window.editFault=editFault;window.deleteButton=deleteButton;window.deleteFault=deleteFault;
init().catch(e=>{console.error(e);alert("حدث خطأ في تشغيل قاعدة البيانات المحلية. جرّب فتح المشروع من Chrome/Edge أو localhost.")});
